
package user;


import java.awt.Color;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class survey extends javax.swing.JFrame {
    private DefaultTableModel data;
    Connection conn;
    Statement stm;
    ResultSet rs;
    /**
     * Creates new form survey
     */
    public survey() {
        initComponents();
        ImageIcon img = new ImageIcon("src/icon/icon.png");
        block();
        Selectkategori();
        Selectuser();
        kode();
        this.setIconImage(img.getImage());
        initUI();
    }
    
    private void initUI(){ 
        getContentPane().setBackground(new Color(245, 245, 245));
        
        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();
        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;    
        setLocation(dx, dy);
    }
    
    protected void block(){
    ids.setEnabled(false);
    nama.setEnabled(false);
    note.setEnabled(false);
    p1.setEnabled(false);
    p2.setEnabled(false);
    p3.setEnabled(false);
    p4.setEnabled(false);
    p5.setEnabled(false);
    p6.setEnabled(false);
    p7.setEnabled(false);
    p8.setEnabled(false);
    p9.setEnabled(false);
    p10.setEnabled(false);
    p10.setEnabled(false);
    ids.setEnabled(false);
    }
    
    protected void kosong(){
    kode();
    }
    
    public void kode() {
        try {
        
            String sql = "SELECT * FROM jawaban ORDER by id_survey desc";
            java.sql.Statement stat = conn.createStatement();
            ResultSet r = stat.executeQuery(sql);

            if (r.next()) {
                String nofak = r.getString("id_survey").substring(1);
                String AN = "" + (Integer.parseInt(nofak) + 1);
                String Nol = "";

                if (AN.length() == 1) {
                    Nol = "000";
                } else if (AN.length() == 2) {
                    Nol = "00";
                } else if (AN.length() == 3) {
                    Nol = "0";
                } else if (AN.length() == 4) {
                    Nol = "";
                }

               ids.setText("S" + Nol + AN);
            } else {
                ids.setText("S0001");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }  
    
    private void Selectkategori(){
        try {Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/survey","root","");
            stm=conn.createStatement();
            String sql = "SELECT * FROM pertanyaan1";
            rs = stm.executeQuery(sql);
            while(rs.next()){
                opsi.addItem(rs.getString("kode_pertanyaan"));
            }
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
            
        }catch(Exception e){
        }
        }
    
    private void Selectuser(){
        try {Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/survey","root","");
            stm=conn.createStatement();
            String sql = "SELECT * FROM db_pelanggan";
            rs = stm.executeQuery(sql);
            while(rs.next()){
                id.addItem(rs.getString("id_pelanggan"));
            }
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
            
        }catch(Exception e){
        }
        }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        op1 = new javax.swing.ButtonGroup();
        op2 = new javax.swing.ButtonGroup();
        op3 = new javax.swing.ButtonGroup();
        op4 = new javax.swing.ButtonGroup();
        op5 = new javax.swing.ButtonGroup();
        op6 = new javax.swing.ButtonGroup();
        op7 = new javax.swing.ButtonGroup();
        op8 = new javax.swing.ButtonGroup();
        op9 = new javax.swing.ButtonGroup();
        op10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        p10 = new javax.swing.JTextField();
        p9 = new javax.swing.JTextField();
        p8 = new javax.swing.JTextField();
        p7 = new javax.swing.JTextField();
        p6 = new javax.swing.JTextField();
        p1 = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        p3 = new javax.swing.JTextField();
        p5 = new javax.swing.JTextField();
        p4 = new javax.swing.JTextField();
        k1 = new javax.swing.JRadioButton();
        k3 = new javax.swing.JRadioButton();
        k4 = new javax.swing.JRadioButton();
        k6 = new javax.swing.JRadioButton();
        k7 = new javax.swing.JRadioButton();
        k9 = new javax.swing.JRadioButton();
        k10 = new javax.swing.JRadioButton();
        k12 = new javax.swing.JRadioButton();
        k13 = new javax.swing.JRadioButton();
        k15 = new javax.swing.JRadioButton();
        k16 = new javax.swing.JRadioButton();
        k18 = new javax.swing.JRadioButton();
        k19 = new javax.swing.JRadioButton();
        k21 = new javax.swing.JRadioButton();
        k22 = new javax.swing.JRadioButton();
        k24 = new javax.swing.JRadioButton();
        k25 = new javax.swing.JRadioButton();
        k27 = new javax.swing.JRadioButton();
        k28 = new javax.swing.JRadioButton();
        save = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        note = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        k30 = new javax.swing.JRadioButton();
        k29 = new javax.swing.JRadioButton();
        k2 = new javax.swing.JRadioButton();
        k5 = new javax.swing.JRadioButton();
        k8 = new javax.swing.JRadioButton();
        k11 = new javax.swing.JRadioButton();
        k14 = new javax.swing.JRadioButton();
        k17 = new javax.swing.JRadioButton();
        k23 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        k26 = new javax.swing.JRadioButton();
        opsi = new javax.swing.JComboBox<>();
        k20 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JComboBox<>();
        nama = new javax.swing.JTextField();
        ids = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SURVEY");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.yellow, java.awt.Color.yellow, java.awt.Color.yellow, java.awt.Color.yellow));
        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 10, 450));
        getContentPane().add(p10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 230, -1));
        getContentPane().add(p9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 230, -1));
        getContentPane().add(p8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 230, -1));

        p7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p7ActionPerformed(evt);
            }
        });
        getContentPane().add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 230, -1));
        getContentPane().add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 230, -1));
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 230, -1));

        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 230, -1));
        getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 230, -1));
        getContentPane().add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 230, -1));
        getContentPane().add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 230, -1));

        op1.add(k1);
        k1.setText("BAIK");
        k1.setOpaque(false);
        getContentPane().add(k1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        op1.add(k3);
        k3.setText("KURANG");
        k3.setOpaque(false);
        getContentPane().add(k3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        op2.add(k4);
        k4.setText("BAIK");
        k4.setOpaque(false);
        getContentPane().add(k4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        op2.add(k6);
        k6.setText("KURANG");
        k6.setOpaque(false);
        getContentPane().add(k6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        op3.add(k7);
        k7.setText("BAIK");
        k7.setOpaque(false);
        getContentPane().add(k7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        op3.add(k9);
        k9.setText("KURANG");
        k9.setOpaque(false);
        getContentPane().add(k9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        op4.add(k10);
        k10.setText("BAIK");
        k10.setOpaque(false);
        getContentPane().add(k10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        op4.add(k12);
        k12.setText("KURANG");
        k12.setOpaque(false);
        getContentPane().add(k12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, -1));

        op5.add(k13);
        k13.setText("BAIK");
        k13.setOpaque(false);
        getContentPane().add(k13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, -1, -1));

        op5.add(k15);
        k15.setText("KURANG");
        k15.setOpaque(false);
        getContentPane().add(k15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, -1, -1));

        op6.add(k16);
        k16.setText("BAIK");
        k16.setOpaque(false);
        getContentPane().add(k16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        op6.add(k18);
        k18.setText("KURANG");
        k18.setOpaque(false);
        getContentPane().add(k18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        op7.add(k19);
        k19.setText("BAIK");
        k19.setOpaque(false);
        getContentPane().add(k19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));

        op7.add(k21);
        k21.setText("KURANG");
        k21.setOpaque(false);
        getContentPane().add(k21, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        op8.add(k22);
        k22.setText("BAIK");
        k22.setOpaque(false);
        getContentPane().add(k22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        op8.add(k24);
        k24.setText("KURANG");
        k24.setOpaque(false);
        getContentPane().add(k24, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        op9.add(k25);
        k25.setText("BAIK");
        k25.setOpaque(false);
        getContentPane().add(k25, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));

        op9.add(k27);
        k27.setText("KURANG");
        k27.setOpaque(false);
        getContentPane().add(k27, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, -1));

        op10.add(k28);
        k28.setText("BAIK");
        k28.setOpaque(false);
        getContentPane().add(k28, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, -1, -1));

        save.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 11)); // NOI18N
        save.setText("SIMPAN");
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 580, 230, 80));

        jLabel7.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID PERTANYAAN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 327, 270, 20));

        note.setColumns(20);
        note.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 13)); // NOI18N
        note.setRows(5);
        note.setText("NOTE:\n\n1.Pilih Kategori Survey\n2.Soal survey akan tampil\n  pada field\n3.Jawab semua survey bedasarkan\n  Penilaian anda\n4.Range Penilaian BAIK, CUKUP, Dan KURANG\n5.Jika sudah klik simpan");
        jScrollPane1.setViewportView(note);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 270, 160));

        jLabel6.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 270, -1));

        op10.add(k30);
        k30.setText("KURANG");
        k30.setOpaque(false);
        getContentPane().add(k30, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, -1, -1));

        op10.add(k29);
        k29.setText("CUKUP");
        k29.setOpaque(false);
        getContentPane().add(k29, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, -1, -1));

        k2.setText("CUKUP");
        k2.setOpaque(false);
        getContentPane().add(k2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        k5.setText("CUKUP");
        k5.setOpaque(false);
        getContentPane().add(k5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        op3.add(k8);
        k8.setText("CUKUP");
        k8.setOpaque(false);
        getContentPane().add(k8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        op4.add(k11);
        k11.setText("CUKUP");
        k11.setOpaque(false);
        getContentPane().add(k11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        op5.add(k14);
        k14.setText("CUKUP");
        k14.setOpaque(false);
        getContentPane().add(k14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, -1, -1));

        op6.add(k17);
        k17.setText("CUKUP");
        k17.setOpaque(false);
        getContentPane().add(k17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        op8.add(k23);
        k23.setText("CUKUP");
        k23.setOpaque(false);
        getContentPane().add(k23, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID PELANGGAN");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 270, -1));

        op9.add(k26);
        k26.setText("CUKUP");
        k26.setOpaque(false);
        getContentPane().add(k26, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, -1, -1));

        opsi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opsi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opsiItemStateChanged(evt);
            }
        });
        getContentPane().add(opsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 260, -1));

        op7.add(k20);
        k20.setText("CUKUP");
        k20.setOpaque(false);
        getContentPane().add(k20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DAFTAR PERTANYAAN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 370, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, -1, -1));

        id.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        id.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                idItemStateChanged(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 260, -1));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 260, 30));
        getContentPane().add(ids, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/bg_jawaban.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new menu_pelanggan().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2ActionPerformed

    private void p7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p7ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String jenis = null;
        String jenis2 = null;
        String jenis3 = null;
        String jenis4 = null;
        String jenis5 = null;
        String jenis6 = null;
        String jenis7 = null;
        String jenis8 = null;
        String jenis9 = null;
        String jenis10 = null;
         if(k1.isSelected()){ jenis = k1.getText();
         }else if (k2.isSelected()){ jenis = k2.getText();
         }else if (k3.isSelected()){ jenis = k3.getText();}
         
         if(k4.isSelected()){ jenis2 = k4.getText();
         }else if (k5.isSelected()){ jenis2 = k5.getText();
         }else if (k6.isSelected()){ jenis2 = k6.getText();}
         
         if(k7.isSelected()){ jenis3 = k7.getText();
         }else if (k8.isSelected()){ jenis3 = k8.getText();
         }else if (k9.isSelected()){ jenis3 = k9.getText();}
         
         if(k10.isSelected()){ jenis4 = k10.getText();
         }else if (k11.isSelected()){ jenis4 = k11.getText();
         }else if (k12.isSelected()){ jenis4 = k12.getText();}
         
         if(k13.isSelected()){ jenis5 = k13.getText();
         }else if (k14.isSelected()){ jenis5 = k14.getText();
         }else if (k15.isSelected()){ jenis5 = k15.getText();}
         
         if(k16.isSelected()){ jenis6 = k16.getText();
         }else if (k17.isSelected()){ jenis6 = k17.getText();
         }else if (k18.isSelected()){ jenis6 = k18.getText();}
         
         if(k19.isSelected()){ jenis7 = k19.getText();
         }else if (k20.isSelected()){ jenis7 = k20.getText();
         }else if (k21.isSelected()){ jenis7 = k21.getText();}
         
         if(k22.isSelected()){ jenis8 = k22.getText();
         }else if (k23.isSelected()){ jenis8 = k23.getText();
         }else if (k24.isSelected()){ jenis8 = k24.getText();}
         
         if(k25.isSelected()){ jenis9 = k25.getText();
         }else if (k26.isSelected()){ jenis9 = k26.getText();
         }else if (k27.isSelected()){ jenis9 = k27.getText();}
         
         if(k28.isSelected()){ jenis10 = k28.getText();
         }else if (k29.isSelected()){ jenis10 = k29.getText();
         }else if (k30.isSelected()){ jenis10 = k30.getText();}
         
            String sql = "insert into jawaban values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, ids.getText());
            stat.setString(2, id.getSelectedItem().toString());
            stat.setString(3, nama.getText());
            stat.setString(4, opsi.getSelectedItem().toString());
            stat.setString(5, jenis);
            stat.setString(6, jenis2);
            stat.setString(7, jenis3);
            stat.setString(8, jenis4);
            stat.setString(9, jenis5);
            stat.setString(10, jenis6);
            stat.setString(11, jenis7);
            stat.setString(12, jenis8);
            stat.setString(13, jenis9);
            stat.setString(14, jenis10);

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data akan disimpan");
            Selectkategori();
            ids.requestFocus();
            kosong();
            }
            catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data gagal disimpan"+e);
 }
    }//GEN-LAST:event_saveActionPerformed

    private void opsiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opsiItemStateChanged
        // TODO add your handling code here:
        String[] opsii = opsi.getSelectedItem().toString().split("//s+");
        String kode = opsii[0];
        if(!kode.equals("Quis")){
            try {
                Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/survey","root","");
            stm=conn.createStatement();
                String nama = "";
                String opsiii = opsi.getSelectedItem().toString();
                switch(opsi.getSelectedIndex()){
                    case 1: nama = "1"; break;
                    case 2: nama = "2"; break;
                    case 3: nama = "3"; break;
                    case 4: nama = "4"; break;
                    case 5: nama = "5"; break;
                    case 6: nama = "6"; break;
                    case 7: nama = "7"; break;
                    case 8: nama = "8"; break;
                    case 9: nama = "9"; break;
                    case 10: nama = "10"; break;
                    case 11: nama = "11"; break;
                    case 12: nama = "12"; break;
                }
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet rs = stm.executeQuery("SELECT * FROM pertanyaan1 WHERE kode_pertanyaan='"+opsiii+"'");
                if(rs.next()){;
                 p1.setText(rs.getString("quis"));
                 p2.setText(rs.getString("quis2"));
                 p3.setText(rs.getString("quis3"));
                 p4.setText(rs.getString("quis4"));
                 p5.setText(rs.getString("quis5"));
                 p6.setText(rs.getString("quis6"));
                 p7.setText(rs.getString("quis7"));
                 p8.setText(rs.getString("quis8"));
                 p9.setText(rs.getString("quis9"));
                 p10.setText(rs.getString("quis10"));
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error " + e);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(survey.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
                }
    }//GEN-LAST:event_opsiItemStateChanged

    private void idItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_idItemStateChanged
        // TODO add your handling code here:
        String[] opsii = id.getSelectedItem().toString().split("//s+");
        String kode = opsii[0];
        if(!kode.equals("ID")){
            try {
                Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/survey","root","");
            stm=conn.createStatement();
                String namas = "";
                String opsiii = id.getSelectedItem().toString();
                switch(id.getSelectedIndex()){
                    case 1: namas = "1"; break;
                    case 2: namas = "2"; break;
                    case 3: namas = "3"; break;
                    case 4: namas = "4"; break;
                    case 5: namas = "5"; break;
                    case 6: namas = "6"; break;
                    case 7: namas = "7"; break;
                    case 8: namas = "8"; break;
                    case 9: namas = "9"; break;
                    case 10: namas = "10"; break;
                    case 11: namas = "11"; break;
                    case 12: namas = "12"; break;
                }
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet rs = stm.executeQuery("SELECT * FROM db_pelanggan WHERE id_pelanggan='"+opsiii+"'");
                if(rs.next()){;
                 nama.setText(rs.getString("nama"));
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error " + e);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(survey.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
                }
    }//GEN-LAST:event_idItemStateChanged
public Connection setKoneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/survey","root","");
            stm=conn.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Koneksi Gagal :" +e);
        }
       return conn; 
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new survey().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> id;
    private javax.swing.JTextField ids;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton k1;
    private javax.swing.JRadioButton k10;
    private javax.swing.JRadioButton k11;
    private javax.swing.JRadioButton k12;
    private javax.swing.JRadioButton k13;
    private javax.swing.JRadioButton k14;
    private javax.swing.JRadioButton k15;
    private javax.swing.JRadioButton k16;
    private javax.swing.JRadioButton k17;
    private javax.swing.JRadioButton k18;
    private javax.swing.JRadioButton k19;
    private javax.swing.JRadioButton k2;
    private javax.swing.JRadioButton k20;
    private javax.swing.JRadioButton k21;
    private javax.swing.JRadioButton k22;
    private javax.swing.JRadioButton k23;
    private javax.swing.JRadioButton k24;
    private javax.swing.JRadioButton k25;
    private javax.swing.JRadioButton k26;
    private javax.swing.JRadioButton k27;
    private javax.swing.JRadioButton k28;
    private javax.swing.JRadioButton k29;
    private javax.swing.JRadioButton k3;
    private javax.swing.JRadioButton k30;
    private javax.swing.JRadioButton k4;
    private javax.swing.JRadioButton k5;
    private javax.swing.JRadioButton k6;
    private javax.swing.JRadioButton k7;
    private javax.swing.JRadioButton k8;
    private javax.swing.JRadioButton k9;
    private javax.swing.JTextField nama;
    private javax.swing.JTextArea note;
    private javax.swing.ButtonGroup op1;
    private javax.swing.ButtonGroup op10;
    private javax.swing.ButtonGroup op2;
    private javax.swing.ButtonGroup op3;
    private javax.swing.ButtonGroup op4;
    private javax.swing.ButtonGroup op5;
    private javax.swing.ButtonGroup op6;
    private javax.swing.ButtonGroup op7;
    private javax.swing.ButtonGroup op8;
    private javax.swing.ButtonGroup op9;
    private javax.swing.JComboBox<String> opsi;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p10;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField p3;
    private javax.swing.JTextField p4;
    private javax.swing.JTextField p5;
    private javax.swing.JTextField p6;
    private javax.swing.JTextField p7;
    private javax.swing.JTextField p8;
    private javax.swing.JTextField p9;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables

    private void Connection() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
