
package master;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class pertanyaan extends javax.swing.JFrame {
private DefaultTableModel data;
    Connection conn;
    Statement stm;
    ResultSet rs;
    /**
     * Creates new form pertanyaan
     */
    public pertanyaan() {
        initComponents();
        ImageIcon img = new ImageIcon("src/icon/icon.png");
        this.setIconImage(img.getImage());
        initUI();
        kosong();
        block();
        tabel();
        kode();
    }
    
    private void initUI(){ 
        getContentPane().setBackground(new Color(245, 245, 245));
        
        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();
        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;    
        setLocation(dx, dy);
    }
    
    protected void block(){
    kp.setEnabled(false);
     }
    
    protected void kosong(){
        save.setEnabled(true);
        edit.setEnabled(false);
        kp.setText("");
        p1.setText("");
        p2.setText("");
        p3.setText("");
        p4.setText("");
        p5.setText("");
        p6.setText("");
        p7.setText("");
        p8.setText("");
        p9.setText("");
        p10.setText("");
        opsi.setSelectedIndex(0);
    }
    
    public void kode() {
        try {
        
            String sql = "SELECT * FROM pertanyaan1 ORDER by kode_pertanyaan desc";
            java.sql.Statement stat = conn.createStatement();
            ResultSet r = stat.executeQuery(sql);

            if (r.next()) {
                String nofak = r.getString("kode_pertanyaan").substring(1);
                String AN = "" + (Integer.parseInt(nofak) + 1);
                String Nol = "";

                if (AN.length() == 1) {
                    Nol = "000";
                } else if (AN.length() == 2) {
                    Nol = "00";
                } else if (AN.length() == 3) {
                    Nol = "0";
                } else if (AN.length() == 4) {
                    Nol = "";
                }

               kp.setText("Q" + Nol + AN);
            } else {
               kp.setText("Q0001");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        p3 = new javax.swing.JTextField();
        p5 = new javax.swing.JTextField();
        p6 = new javax.swing.JTextField();
        p7 = new javax.swing.JTextField();
        p4 = new javax.swing.JTextField();
        p8 = new javax.swing.JTextField();
        p9 = new javax.swing.JTextField();
        p10 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        kp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        opsi = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PERTANYAAN");
        setPreferredSize(new java.awt.Dimension(900, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 250, 40));
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 250, 40));
        getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 250, 40));
        getContentPane().add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 250, 40));
        getContentPane().add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 250, 40));
        getContentPane().add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 250, 40));
        getContentPane().add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 250, 40));
        getContentPane().add(p8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 250, 40));
        getContentPane().add(p9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 250, 40));
        getContentPane().add(p10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 250, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, -1, -1));

        save.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 11)); // NOI18N
        save.setText("SIMPAN");
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 250, -1));

        edit.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 11)); // NOI18N
        edit.setText("UBAH");
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, 250, -1));

        delete.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 11)); // NOI18N
        delete.setText("HAPUS");
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 590, 250, -1));

        batal.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 11)); // NOI18N
        batal.setText("BATAL");
        batal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        getContentPane().add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, 250, -1));
        getContentPane().add(kp, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 250, -1));

        jLabel5.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("KODE PERTANYAAN?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 270, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TABEL PERTANYAAN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 400, -1));

        cari.setText("Cari...");
        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cariKeyPressed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 540, -1));

        jLabel3.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("KATEGORI ?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 270, -1));

        tabel.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 11)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 517, 540, 130));

        opsi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KATEGORI 1", "KATEGORI 2", "KATEGORI 3" }));
        opsi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(opsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 250, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/bg_jawaban.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"Hapus data ini?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (ok==0){
            String sql = "delete from pertanyaan1 where kode_pertanyaan ='"+kp.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data akan di hapus dari sistem?");
                kosong();
                kode();
                kp.requestFocus();
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+e);
            }
            tabel();
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        kosong();
        kode();
        tabel();
    }//GEN-LAST:event_batalActionPerformed

    private void cariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyPressed
        // TODO add your handling code here:
        Object header[]={"KODE PERTANYAAN","QUIS","QUIS2","QUIS3","QUIS4","QUIS5","QUIS5","QUIS6","QUIS7","QUIS8","QUIS9","QUIS10","KATEGORI"};
        DefaultTableModel data=new DefaultTableModel(null,header);
        tabel.setModel(data);

        setKoneksi();
        String sql="Select * from pertanyaan1 where kode_pertanyaan like '%" + cari.getText() + "%'" +"or quis like '%" + cari.getText()+"%'";

        try {
            ResultSet rs=stm.executeQuery(sql);
            while (rs.next())
            {
                String kolom1=rs.getString("kode_pertanyaan");
                String kolom2=rs.getString("quis");
                String kolom3=rs.getString("quis2");
                String kolom4=rs.getString("quis3");
                String kolom5=rs.getString("quis4");
                String kolom6=rs.getString("quis5");
                String kolom7=rs.getString("quis6");
                String kolom8=rs.getString("quis7");
                String kolom9=rs.getString("quis8");
                String kolom10=rs.getString("quis9");
                String kolom11=rs.getString("quis10");
                String kolom12=rs.getString("kategori");

                String kolom[]={kolom1,kolom2,kolom3,kolom4,kolom5,kolom6,kolom7,kolom8,kolom9,kolom10,kolom11,kolom12};
                data.addRow(kolom);
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_cariKeyPressed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
           int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Untuk Update data ini???","Confirmation",JOptionPane.YES_NO_OPTION);
         try
            {
                String sql="update pertanyaan1 set "
                        + "kode_pertanyaan=?,"
                        + "quis=?,"
                        + "quis2=?,"
                        + "quis3=?,"
                        + "quis4=?,"
                        + "quis5=?,"
                        + "quis6=?,"
                        + "quis7=?,"
                        + "quis8=?,"
                        + "quis9=?,"
                        + "quis10=?,"
                        + "kategori=?, "
                        + "where kode_pertanyaan='"+kp.getText()+"'";
                PreparedStatement st=conn.prepareStatement(sql);
                if(ok==0)
                {
                try
                    {
                        st.setString(1,p1.getText());
                        st.setString(2,p2.getText());
                        st.setString(3,p3.getText());
                        st.setString(4,p4.getText());
                        st.setString(5,p5.getText());
                        st.setString(6,p6.getText());
                        st.setString(7,p7.getText());
                        st.setString(8,p8.getText());
                        st.setString(9,p9.getText());
                        st.setString(10,p10.getText());
                        st.executeUpdate();

                        JOptionPane.showMessageDialog(null,"Update Data Sukses");
                    }catch (Exception e)
                    {
                        JOptionPane.showMessageDialog(null, "Update Data Gagal");
                    }
                }
           }catch (Exception e){}
    }//GEN-LAST:event_editActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String jenis = null;
            String sql = "insert into pertanyaan1 values (?,?,?,?,?,?,?,?,?,?,?,?)";
            try{
            PreparedStatement stat = conn.prepareStatement(sql);
            
            stat.setString(1, kp.getText());
            stat.setString(2, p1.getText());
            stat.setString(3, p2.getText());
            stat.setString(4, p3.getText());
            stat.setString(5, p4.getText());
            stat.setString(6, p5.getText());
            stat.setString(7, p6.getText());
            stat.setString(8, p7.getText());
            stat.setString(9, p8.getText());
            stat.setString(10, p9.getText());
            stat.setString(11, p10.getText());
            stat.setString(12, opsi.getSelectedItem().toString());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data akan disimpan");
            kosong();
            kp.requestFocus();
            tabel();
            kode();
            }
            catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data gagal disimpan"+e);
             tabel();
 }
    }//GEN-LAST:event_saveActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        save.setEnabled(false);
        edit.setEnabled(true);
        int baris = tabel.getSelectedRow();
        kp.setText(tabel.getModel().getValueAt(baris, 0).toString());
        p1.setText(tabel.getModel().getValueAt(baris, 1).toString());
        p2.setText(tabel.getModel().getValueAt(baris, 2).toString());
        p3.setText(tabel.getModel().getValueAt(baris, 3).toString());
        p4.setText(tabel.getModel().getValueAt(baris, 4).toString());
        p5.setText(tabel.getModel().getValueAt(baris, 5).toString());
        p6.setText(tabel.getModel().getValueAt(baris, 6).toString());
        p7.setText(tabel.getModel().getValueAt(baris, 7).toString());
        p8.setText(tabel.getModel().getValueAt(baris, 8).toString());
        p9.setText(tabel.getModel().getValueAt(baris, 9).toString());
        p10.setText(tabel.getModel().getValueAt(baris, 10).toString());
        opsi.setSelectedItem(tabel.getModel().getValueAt(baris, 11).toString());
    }//GEN-LAST:event_tabelMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new menu_own().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked
public Connection setKoneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/survey","root","");
            stm=conn.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Koneksi Gagal :" +e);
        }
       return conn; 
    }
    
    public void tabel(){
        Object header[]={"KODE PERTANYAAN","QUIS","QUIS2","QUIS3","QUIS4","QUIS5","QUIS5","QUIS6","QUIS7","QUIS8","QUIS9","QUIS10","KATEGORI"};
        DefaultTableModel data=new DefaultTableModel(null,header);
        tabel.setModel(data);

        setKoneksi();
        String sql="Select * from pertanyaan1 where kode_pertanyaan like '%" + cari.getText()
                + "%'" +"or quis like '%" 
                 + "%'" +"or quis2 like '%" 
                 + "%'" +"or quis3 like '%" 
                 + "%'" +"or quis4 like '%" 
                 + "%'" +"or quis5 like '%" 
                 + "%'" +"or quis6 like '%" 
                 + "%'" +"or quis7 like '%" 
                 + "%'" +"or quis8 like '%" 
                 + "%'" +"or quis9 like '%" 
                 + "%'" +"or quis10 like '%" 
                + cari.getText()+"%'";

        try {
            ResultSet rs=stm.executeQuery(sql);
            while (rs.next())
            {
                String kolom1=rs.getString("kode_pertanyaan");
                String kolom2=rs.getString("quis");
                String kolom3=rs.getString("quis2");
                String kolom4=rs.getString("quis3");
                String kolom5=rs.getString("quis4");
                String kolom6=rs.getString("quis5");
                String kolom7=rs.getString("quis6");
                String kolom8=rs.getString("quis7");
                String kolom9=rs.getString("quis8");
                String kolom10=rs.getString("quis9");
                String kolom11=rs.getString("quis10");
                String kolom12=rs.getString("kategori");

                String kolom[]={kolom1,kolom2,kolom3,kolom4,kolom5,kolom6,kolom7,kolom8,kolom9,kolom10,kolom11,kolom12};
                data.addRow(kolom);
            }

        } catch (Exception e) {
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pertanyaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pertanyaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pertanyaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pertanyaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pertanyaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JTextField cari;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kp;
    private javax.swing.JComboBox<String> opsi;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p10;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField p3;
    private javax.swing.JTextField p4;
    private javax.swing.JTextField p5;
    private javax.swing.JTextField p6;
    private javax.swing.JTextField p7;
    private javax.swing.JTextField p8;
    private javax.swing.JTextField p9;
    private javax.swing.JButton save;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
